### ISSUE TITLE
The new Settings page

### ISSUE THREAD

**Issue by warpech** [StarcounterAppsFreezer/Launcher#177]
As discussed in https://github.com/Starcounter/RebelsLounge/issues/7, I have added a simple `/launcher/settings` page that displays settings from all the mapped apps. 

It is accessible by clicking on the cog icon here:

<img width="1436" alt="screen shot 2015-12-09 at 13 13 26" src="https://cloud.githubusercontent.com/assets/566463/11685076/a6dcb048-9e76-11e5-869a-64366a5639ae.png">

As I have seen in RSE Launcher (@jwillmer), this does not necessarily have to open a new page. In case of that launcher, it is just a pane that opens from the right side of the screen.

Let's discuss any potential improvements here.

It is now only roughly explained on page: http://starcounter.io/guides/web/launcher/

**Comment by malx122** [comment]
Since we already have this feature (But not implemented in launcher, instead our own common library) I can tell you about our implementation.
```
            Handle.GET("/tunity_gantt/settings_menu", (Request req) =>
            {
                var menu = new Menu() { Name = "tunity_gantt" };
                menu.Items.Add(new MenuItem()
                {
                    Label = "Activity roles",
                    Icon = "user-secret",
                    Url = "/tunity_gantt/settings/activity_roles",
                });
                menu.Items.Add(new MenuItem()
                {
                    Label = "Templates",
                    Icon = "align-right",
                    Url = "/tunity_gantt/settings/templates",
                }); return menu;
            });
```
This falls back to the same issue as other menus/search e.t.c. The json must be structured if you gonna get any consistency between apps. This is a priority and custom-ability comes as far, far second. (But might still be a possibility). For launcher, the above icon property must for example be replaced with a html since it can be anything.

**Comment by malx122** [comment]
For the menu itself, our implementation looks like:
```
				<template is="dom-repeat" items="{{_getItems(model.CommonMenu)}}">
					<a href$="{{item.Url}}" id="item" class$="{{_calcItemClass(item.Url, model._url)}}">
						<div class="horizontal center">
							<tu-icon icon="{{item.Icon}}"></tu-icon>
							<span class="label">{{item.Label}}</span>
						</div>
					</a>
				</template>
```
Where the _getItems function is
```
template._getItems = function(menu) {
				 var items = [];
				 for (var name in menu)
				 {
					 if (menu.hasOwnProperty(name) && menu[name].hasOwnProperty("Items")) {
						for (var i = 0; i < menu[name].Items.length; i++) {
							items.push(menu[name].Items[i]);
						}
					 }
				 }
				 return items;
			 };
```
This has a drawback. It actually breaks the polymer update system inside the repeat. It not a big issue though, since menu items seldom changes while showing. (I also have a workaround if needed)

**Comment by malx122** [comment]
The last part is showing the selected. Our settings menu are on the left (since our head menu is on the top) and is always showing, Therefore we wanted to show the current setting as selected.

I designed a url-watcher:
```
<tu-url-watcher url="{{model._url}}"></tu-url-watcher>
```
This one updates model._url with the "window.location.href". It actually uses a timer since there are no reliable events that works on all browser and with all methods of updating this property. (Puppyjs ca maybe tell?). This timer however takes very little overhead.

and by having the class property depend on it:
```
class$="{{_calcSelected(item.Url, model._url);
```
(Updates just on model._url changes, not item.Url since the _getItems method above broke that one)
```
template._calcItemClass = function(url1, url2) {
				 var selected = (typeof url2 == 'string')? url2.indexOf(url1) !== -1: false;
			   	 return  "horizontal center item" + (selected?" selected": "");
			 };
```

**Comment by warpech** [comment]
The more general version is now being discussed in: https://github.com/Starcounter/Guidelines/issues/33

**Comment by warpech** [comment]
Archiving
